from .admin import AdminApi
from .official_account import OfficialAccountApi
from .user import UserApi
from .qy import QyApi
from .equipment import EquipmentApi
from .favor import FavorApi
from .finder import FinderApi
from .friend import FriendApi
from .group import GroupApi
from .label import LabelApi
from .message import MessageApi
from .other import OtherApi
from .pay import PayApi
from .sns import SnsApi
